s = ()
n1 = int(input("Enter the value of n1: "))
s.add(n1)
n2 = int(input("Enter the value of n2: "))
s.add(n2)
n3 = int(input("Enter the value of n3: "))
s.add(n3)
n4 = int(input("Enter the value of n4: "))
s.add(n4)
n5 = int(input("Enter the value of n5: "))
s.add(n5)
n6 = int(input("Enter the value of n6: "))
s.add(n6)
n7 = int(input("Enter the value of n7: "))
s.add(n7)
n8 = int(input("Enter the value of n8: "))
s.add(n8)

print(s)