music = {
    "news": "https://www.youtube.com/live/Nq2wYlWFucg?si=Xcls0PkB4nTzPzWw",
    "agam": "https://youtu.be/bfyQ3FIkDXI?si=ekVI0Pm7tpe9Pxbc",
    "march": "https://www.youtube.com/watch?v=Xqeq4b5u_Xw",
    "skyfall": "https://www.youtube.com/watch?v=DeumyOzKqgI&pp=ygUHc2t5ZmFsbA%3D%3D",
    "aankhon": "https://youtu.be/PwEvz2FLZ4I?si=J_9JnyK496RLjxYC",
    "smile": "https://youtu.be/kPa7bsKwL-c?si=z8abrf-FOIbcO2UZ",
    "saanson": "https://youtu.be/4jKkT3d8gdI?si=GvKV5e9hptoG2L0i",
    "ishq": "https://youtu.be/hHuG7FIKgtc?si=URTI8S2J5a_Ce0zs",
    "hanging": "https://youtu.be/F3hTW9e20d8?si=U081QCY3-ZX_0WZe",
    "aasman": "https://youtu.be/FT-zo5Kgp2U?si=9_qWZK9UntyjPC77",
    "raja": "https://youtu.be/gmyRw66w4uA?si=XnS8_QkgaOB91U6_",
    "pahin": "https://youtu.be/2CnatpIv8qQ?si=WiHEDWp5rqnEkX3y",
    "baccha": "https://youtu.be/AtnB0DbuFFU?si=wk47t-_QDYpZzMJx",
    "gangi": "https://youtu.be/Njyx5ZuwEHI?si=5H5wwg8kM23wuWom",
    "tony": "https://youtu.be/IN4bsmwLwjg?si=NvldATitHGT2plHj",
    "kolav": "https://youtu.be/YR12Z8f1Dh8?si=L4aX3z15g2hFV3D4",
    "mere ho": "https://youtu.be/ilNt2bikxDI?si=RwZxEd-da36GpzC3",
    "sajni": "https://youtu.be/k3g_WjLCsXM?si=ai5-2o2ze7y54wTh",
    "appa": "https://youtu.be/DLZD47lj82o?si=j6kXr5LyzqnqZDTH",
    "tu": "https://youtu.be/A66TYFdz8YA?si=GfVTTfOMB1wfEg0S",
    "palang": "https://youtu.be/igQCv_Y33NI?si=q7sfRWEmaJqvngyc",
    "chalu": "https://youtu.be/71yzX1SA56A?si=QrHKJxNf-tgkXIXX",
    "aaj": "https://youtu.be/hxMNYkLN7tI?si=bP4rHk7yiaudCwTZ",
    "chhammak": "https://youtu.be/oAVhUAaVCVQ?si=xpKl0-Aez5YiCZzx"
}